# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(698, 503)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.btnUV4 = QtWidgets.QPushButton(self.centralwidget)
        self.btnUV4.setGeometry(QtCore.QRect(420, 40, 98, 23))
        self.btnUV4.setObjectName("btnUV4")
        self.txtUV4 = QtWidgets.QTextEdit(self.centralwidget)
        self.txtUV4.setGeometry(QtCore.QRect(160, 30, 251, 41))
        self.txtUV4.setObjectName("txtUV4")
        self.txtPrj = QtWidgets.QTextEdit(self.centralwidget)
        self.txtPrj.setGeometry(QtCore.QRect(160, 120, 251, 31))
        self.txtPrj.setObjectName("txtPrj")
        self.btnPrj = QtWidgets.QPushButton(self.centralwidget)
        self.btnPrj.setGeometry(QtCore.QRect(420, 120, 101, 31))
        self.btnPrj.setObjectName("btnPrj")
        self.btnCompile = QtWidgets.QPushButton(self.centralwidget)
        self.btnCompile.setGeometry(QtCore.QRect(220, 220, 75, 23))
        self.btnCompile.setObjectName("btnCompile")
        self.txtCompileResult = QtWidgets.QTextEdit(self.centralwidget)
        self.txtCompileResult.setGeometry(QtCore.QRect(160, 310, 251, 71))
        self.txtCompileResult.setObjectName("txtCompileResult")
        Form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 698, 23))
        self.menubar.setObjectName("menubar")
        Form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form)
        self.statusbar.setObjectName("statusbar")
        Form.setStatusBar(self.statusbar)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MainWindow"))
        self.btnUV4.setText(_translate("Form", "更改UV4.EXE路径"))
        self.btnPrj.setText(_translate("Form", "更改项目路径"))
        self.btnCompile.setText(_translate("Form", "编译并烧录"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
